### ISSUE TITLE
Promocionar el Mapatón de Establecimeintos de Salud en el sitio web

### ISSUE THREAD

**Issue by caprieldeluca** [osm-ar/osm-argentina-website#12]
Hola!,

por unos días, se podría cambiar el popup del sitio web para que muestre [el flyer del mapatón](https://wiki.openstreetmap.org/wiki/File:Primer_Mapaton_-_COVID19_-_OSM_Argentina.png), y que el botón del enlace vaya a [la wiki del evento](https://wiki.openstreetmap.org/wiki/ES:Argentina/Eventos/Mapat%C3%B3n_Salud_2020) en vez de a la del proyecto COVID19?

Sería por este fin de semana y revertirlo el lunes.

**Comment by juanblas09** [comment]
Muy buena idea, podríamos reemplazarla por el pop-up que está ahora

**Comment by juanblas09** [comment]
Me asigno la tarea y la hago

**Comment by juanblas09** [comment]
![imagen](https://user-images.githubusercontent.com/20421887/81355091-b5a85b80-90a3-11ea-8d37-5984e3d29332.png)

**Comment by caprieldeluca** [comment]
Para mí está genial así

**Comment by juanblas09** [comment]
Recordar retirar cuando termine el evento

**Comment by ignaciolep** [comment]
Quedó excelente el flyer en el popup.
¿Se podrá agregarle el link a la [wiki del mapatón](https://wiki.openstreetmap.org/wiki/ES:Argentina/Eventos/Mapat%C3%B3n_Salud_2020) en la imágen?

**Comment by juanblas09** [comment]
Ahora si!

**Comment by caprieldeluca** [comment]
> Recordar retirar cuando termine el evento

Terminó el evento :-)

**Comment by juanblas09** [comment]
Gracias Gabrielo!! Ya lo edito
