### ISSUE TITLE
Logo oficial OpenStreetMap Argentina

### ISSUE THREAD

**Issue by ignaciolep** [osm-ar/osm-argentina-website#3]
Cómo el sitio tenía el logo con la URL vieja (osmargentina.org) lo comenté en el index para que no se muestre.

Habría que subir un logo con el ícono oficial (https://wiki.openstreetmap.org/wiki/File:OSM_Argentina_Logo.svg) y el texto OpenStreetMap Argentina.

**Comment by juanblas09** [comment]
Necesariamente tiene que ser el logo oficial, o podemos hacer una modificación del anterior?

**Comment by ignaciolep** [comment]
> Necesariamente tiene que ser el logo oficial, o podemos hacer una modificación del anterior?

Podría ser. En www.openstreetmap.us usan una versión simplificada. Lo que creo que es importante es que diga "OpenStreetMap Argentina" y no "OSM" porque alguien fuera de la comunidad puede no entender la referencia.

**Comment by juanblas09** [comment]
@ignaciolep Ahí subí un branch con una versión con el logo viejo pero con la dirección actualizada, aunque se me ocurrieron otras ideas ahora para poder poner "OpenStreetMap Argentina" sin que quede excesivamente largo

**Comment by juanblas09** [comment]
O en todo caso, "OpenStreetMap AR" similar a como aparecemos en algunas redes sociales

**Comment by ignaciolep** [comment]
Si queres adjunta las versiones imagenes por acá y lo vemos más fácil

**Comment by juanblas09** [comment]
En eso estaba, pasa que me quedé pensando

![Foto](https://i.ibb.co/Fgjpg4M/Captura.png)

**Comment by juanblas09** [comment]
Me sigo quedando con la 1º

**Comment by ignaciolep** [comment]
> Me sigo quedando con la 1º

Yo igual

**Comment by juanblas09** [comment]
Ya está implementada la nueva versión del logo
