### ISSUE TITLE
Nueva frontpage para http://openstreemap.org.ar/

### ISSUE THREAD

**Issue by mrtngrsbch** [osm-ar/osm-argentina-website#5]
Aloha,

Propongo que, para este perído de crisis y en respuesta al proyecto COVIR [https://wiki.openstreetmap.org/wiki/ES:Argentina/COVID-19] pongamos en la home ese mapa, u otro pertinente.
Esto es SOLO requerimiento de negocio: Atender la emergencia con una frontpage acorde.

salut

**Comment by caprieldeluca** [comment]
Hola!  
Respecto del mapa del proyecto [Argenitna/COVID-19](https://wiki.openstreetmap.org/wiki/ES:Argentina/COVID-19), lo armé para que podamos comparar los datos de los listados de establecimientos que están en la wiki con los datos que hay en OSM, para hacer los agregados o modificaciones que sean necesarios.  

Es decir, no sólo tiene las capas de las consultas overpass, que las actualizo con frecuencia variable (cuando puedo o me lo pidan, últimamente cada día y medio), sino las capas de datos de las otras fuentes del proyecto, para compararlas.  

Además, algunos de esos listados no estaban georreferenciados y les corrí un geocode Nominatim a los listados CSV (caso de las farmacias de PAMI y de los CAPS de Remediar).  Dado que en muchas localidades del interior faltan las alturas de las calles (y en muchos establecimientos de los listados las direcciones están escritas o con otro nombre de calle o sin número, etc), el geocode salió bastante impreciso.

Los datos de las capas de ese mapa están en mi repositorio [covid-19](https://github.com/gabriel-de-luca/covid-19).

Si quieren poner un enlace a la wiki del proyecto y/o al mapa, me parece bien porque ayudaría a darle difusión al proyecto, pero para superoner ambos mapas me parece mejor que sean sólo los datos de OSM.

En ese caso me parece incluso mejor, porque el mapa de OpenStreetMap Argentina estaría remarcando los establecimientos de salud de OSM y eso es importante en esta emergencia. 

Habría que ver la manera de superponer las consultas en tiempo real si es posible. Yo no supe la manera de hacerlo en el uMap del proyecto, así que opté por descargar los geojson de la consulta y actualizar el repositorio.

**Comment by mrtngrsbch** [comment]
Me parece perfecto cualquier medida que se pueda implementar en un tiempo razonable, cuestión de ser útil.
personalmente y para este caso, prefiero concentrarme en el requerimiento de negocio, que podría ampliarlo a los centros de vacunación de los cuales, pronto seré voluntario

**Comment by ignaciolep** [comment]
> pongamos en la home ese mapa

Ese mapa es para tener una idea de lo que falta mapear, en todo caso se podría agregar una entrada de menú que lleve a la página del proyecto.

> Habría que ver la manera de superponer las consultas en tiempo real si es posible. Yo no supe la manera de hacerlo en el uMap del proyecto, así que opté por descargar los geojson de la consulta y actualizar el repositorio.

Mejor continuar con los GeoJson. Carlos Brys explicó que sino por cada visita al mapa realizaría la consulta en Overpass, sobrecargando innecesariamente el servidor.

**Comment by mrtngrsbch** [comment]
1. ok por agregar link a ese proyecto, y si es un splash de inicio mejor. Tiene que ser muy visible y luego poder viralizarlo
2. si, claro... un geojson actualizado a diario es más que sufi

**Comment by juanblas09** [comment]
Concuerdo con @ignaciolep, deberíamos ponerlo como link en el navbar, a lo sumo un alert cuando se ingresa a la página, pero no lo pondría como mapa por defecto

**Comment by mrtngrsbch** [comment]
1. Si se puede implementar un splash como el que tiene Ciudad ahora, sería estupendo
https://www.buenosaires.gob.ar/
2. Ahora estoy buscando los centros de vacunación, que podríamos incluir
3. Sería ideal que este nuevo mapa json tenga su propia URL también

**Comment by mrtngrsbch** [comment]
Estimados...
Aquí el link a los centros de vacunación de CABA
https://www.buenosaires.gob.ar/sites/gcaba/files/segmentacion_y_postas-vacunacion-adultos-mayores.pdf

Ni idea de como los podríamos agregar a OSM... pregunto enel telegram

**Comment by juanblas09** [comment]
Después averiguo como hacerlo sin bootstrap

**Comment by juanblas09** [comment]
Y lo cargo (esta noche)

**Comment by juanblas09** [comment]
![Screenshot_2020-04-06 OpenStreetMap Argentina](https://user-images.githubusercontent.com/20421887/78612800-961dd900-7840-11ea-9c0d-aaa8b61ea017.png)

**Comment by juanblas09** [comment]
Listo, agregado a la web

**Comment by caprieldeluca** [comment]
Quedó muy bien! 
Propongo unos cambios (en negrita) en el texto del aviso:

> Te presentamos el nuevo mapa de soporte de datos y visualización para el proyecto de mapeo de OpenStreetMap **Argentina** relacionado a la actual pandemia del Covid-19. Puede visitarlo **haciendo** clic en el enlace "COVID-19" del menú.

El tema es que OpenStreetMap tiene otros proyectos covid19.

**Comment by juanblas09** [comment]
Gracias por la apreciación @gabriel-de-luca !

Ahí se corrigió el texto, no había pensado en lo de "Argentina", y el "haciendo" lo omití de apurado, gracias!
